export const START_NEW_GAME = 'START_NEW_GAME';
export const ATTEMPT_ANSWER = 'ATTEMPT_ANSWER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
